name: studentchatbot
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-292.0.dev <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  dialog_flowtter: ^0.3.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
